services:
  frontend:
    env_file:
      - .env
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: yarn dev
    volumes:
      - '.:/app'
      - '/app/node_modules'
    working_dir: /app
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
